//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Assessment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assessment()
        {
            this.registrations = new HashSet<registration>();
        }

        [Display(Name = "Assessment ID")]
        public int Assessment_Id { get; set; }
        [Display(Name = "Student ID")]
        public int Student_ID { get; set; }
        [Display(Name = "Course ID")]
        public int Course_ID { get; set; }
        [Display(Name = "Individual Course Assessment Marks")]
        public string ICAM { get; set; }
        [Display(Name = "Final Examination Marks")]
        public string FEM { get; set; }
        [Display(Name = "Course Grade")]
        public string Course_Grade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<registration> registrations { get; set; }
    }
}
