//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.registrations = new HashSet<registration>();
        }
    
        public int Id { get; set; }
        [Display(Name = "Course Code")]
        [Required(ErrorMessage = "This field is required")]
        public string Course_Code { get; set; }
        [Display(Name = "Course Name")]
        [Required(ErrorMessage = "This field is required")]
        public string Course_Name { get; set; }
        [Display(Name = "Year Offered")]
        [Required(ErrorMessage = "This field is required")]
        public string Year_Offered { get; set; }
        [Display(Name = "Semester Offered")]
        [Required(ErrorMessage = "This field is required")]
        public string Semester_Offered { get; set; }
        public string Fees { get; set; }
        [Display(Name ="Teacher Name")]
        public string Teacher { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<registration> registrations { get; set; }
    }
}
