//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.registrations = new HashSet<registration>();
        }
    
        [Display(Name ="Student ID")]
        public int Student_ID { get; set; }
        [Display(Name = "First Name")]
        [Required(ErrorMessage = "This field is required")]
        public string First_Name { get; set; }
        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "This field is required")]
        public string Last_Name { get; set; }
        public string Address { get; set; }
        [Display(Name = "Contact Detail")]
        [Required(ErrorMessage = "This field is required")]
        public string Contact_Detail { get; set; }
        [Display(Name = "Education Background")]
        [Required(ErrorMessage = "This field is required")]
        public string Education_Background { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<registration> registrations { get; set; }
    }
}
